// @ts-check
import { defineConfig } from 'astro/config';
import rehypeSlug from 'rehype-slug';
import remarkSmartypants from 'remark-smartypants';
import { remarkKramdownIAL } from './src/lib/remark-kramdown-ial.mjs';
import { rehypeUndoAutolinks } from './src/lib/rehype-undo-autolinks.mjs';

// User site served at the domain root. Unlike the frequency project site, base is '/'
// (do NOT set a subpath base) and a CNAME must ship in the build output (public/CNAME)
// or the custom domain drops. trailingSlash:'always' matches the Jekyll /:path/
// permalinks and the root, so canonicals and internal links stay byte-identical.
export default defineConfig({
  site: 'https://shadowingkit.com',
  base: '/',
  trailingSlash: 'always',
  // Sitemap is generated by src/pages/sitemap.xml.ts (a single /sitemap.xml matching
  // the jekyll-sitemap path that robots.txt and Search Console already reference),
  // not @astrojs/sitemap (which would emit sitemap-index.xml at a new path).
  markdown: {
    // Match Kramdown's output: heading IDs (auto_ids) + smart typography
    // (curly quotes, en/em dashes, ellipses). Kept so the ported article bodies
    // read byte-for-byte like the Jekyll pages.
    // Built-in smartypants is disabled so remarkKramdownIAL runs on the raw straight
    // quotes BEFORE remark-smartypants curls them; otherwise the IAL marker leaks.
    smartypants: false,
    rehypePlugins: [rehypeSlug, rehypeUndoAutolinks],
    remarkPlugins: [remarkKramdownIAL, remarkSmartypants],
  },
});
